version: '3.3'

services:
  web:
    # image: registry.gitlab.com/....
    build: .
    ports:
      - '8002:3000'
    environment:
      API_BASE_URL: https://api.example.com
      RUNTIME_API_KEY: 1234567890
      NEXT_PUBLIC_APP_ENV: development
      NEXT_PUBLIC_APP_PUBLIC_KEY: public-key
      ENV_VARIABLES: '$$NEXT_PUBLIC_APP_ENV,$$NEXT_PUBLIC_APP_PUBLIC_KEY'